### ISSUE TITLE
how to contact ariafan 

### ISSUE THREAD

**Issue by mahmoud-10th** [ariafan/android_kernel_xiaomi_msm8916#1]
hello mr ariafan i have an issue on building kernel i would like to contact you by email or chat because i can't sign in to 4pda but i can sign in to vk / facebook 
please tell me how can i contact you .
thank you .

**Comment by ariafan** [comment]
you can contact me on telegram @araifan4pda

**Comment by mahmoud-10th** [comment]
thank you sir
